package com.OnTime.ontime.data.models

import java.util.Date

data class NotificationRecord(
    val id: String = "", // Unique ID for the record, can be generated by Firebase
    val userId: String = "", // User who received the notification
    val eventId: String = "", // ID of the calendar event
    val eventTitle: String = "", // Title of the calendar event
    val notificationMessage: String = "", // The personalized message generated by Gemini
    val timestamp: Date = Date(), // When the notification was generated/sent
    val estimatedTravelTimeMinutes: Int = 0, // Google Maps ETA
    val actualTravelTimeMinutes: Int = 0, // Predicted or tracked actual travel time
    val weatherInfo: String = "", // Weather info at the time
    val messageTone: String = "" // e.g., "친근한", "격식있는"
)
